<?php

/**
 * @file
 * The node_convert_with_template module converts nodes from one type to another using template.
 */

/**
 * Implements hook_menu().
 */
function node_convert_with_template_menu() {
  $items = array();

  $items['node/%/convert-with-template/%'] = array(
    'title' => 'Convert with template',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('node_convert_with_template_conversion_form', 1, 3),
    'access callback' => 'node_convert_check_access',
    'access arguments' => array(1),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function node_convert_with_template_conversion_form($form, $form_state, $nid, $tplid) {
  $form['nid'] = array(
    '#type' => 'hidden',
    '#value' => check_plain($nid),
  );
  $form['tplid'] = array(
    '#type' => 'hidden',
    '#value' => check_plain($tplid),
  );

  $question = t('Are you sure you convert this node ?');
  return confirm_form($form, $question, 'node/' . $nid, '', t('Yes'), t('Cancel'));
}

function node_convert_with_template_conversion_form_submit($form, &$form_state){
  node_convert_convert_nodes_using_template((array) $form_state['values']['nid'], $form_state['values']['tplid'] );
  drupal_goto('node/' . $form_state['values']['nid'] );
}
